### ISSUE TITLE
feature request, to change saber trail width because we already have length, just width next.

### ISSUE THREAD

**Issue by mythiculs** [qqrz997/CustomSabersLite#20] opened 2024-06-12 18:42 UTC

**Comment by mythiculs** [comment] 2024-06-12 18:42
Saber Length makes it Longer / Shorter, but width makes it thinner or bigger, and it would be cool.

**Comment by qqrz997** [comment] 2024-06-13 14:16
Duplicate of #19

**Closed by qqrz997** 2024-06-13 14:16 UTC
Labels: duplicate
