### ISSUE TITLE
[Bug] Saber can be disoriented one song start.

### ISSUE THREAD

**Issue by 1Alyng** [qqrz997/CustomSabersLite#15] opened 2024-05-29 16:41 UTC
The saber gets moved into the wrong position and rotation.
Is fixxable by disabiling "Override Trail Width" and reenabiling it.
I have only tested this on .whacker files!
Update: seems to happen a lot more with the mods tab menu than the actually CSL mod menu
Update 2: It happens everywhere, with all saber files, and even with everything off!

**Comment by qqrz997** [comment] 2024-05-30 18:33
i'll have a fix for this soon but in the meantime just restarting a map should fix it

**Comment by qqrz997** [comment] 2024-05-31 13:58
fixed in latest https://github.com/qqrz997/CustomSabersLite/tree/v0.10.2

**Comment by 1Alyng** [comment] 2024-05-31 17:47
I have this issue on newest

**Comment by qqrz997** [comment] 2024-06-02 12:42
i can't reproduce this anymore, the saber model wasn't parented correctly and this has been amended

**Comment by 1Alyng** [comment] 2024-06-03 14:03
Issue seemed to have fixed itself after installing easy offset

**Comment by qqrz997** [comment] 2024-06-03 16:41
closing this until someone finds any way to produce this bug. i have tried over and over and cannot get this to happen.

**Closed by qqrz997** 2024-06-03 16:41 UTC
Labels: bug
