### ISSUE TITLE
make it more like saberfactory

### ISSUE THREAD

**Issue by Flicksybs** [qqrz997/CustomSabersLite#31] opened 2024-11-17 20:39 UTC
it would be great to have the button in the base game settings like saberfactory, aswell as the same list with folders and a search bar, with the seperate tabs for trails and such

**Comment by qqrz997** [comment] 2024-11-18 11:09
folders are planned, and trail selection is maybe planned. i am not going to modify the player tabs. otherwise this is essentially a duplicate of #27 and #17

**Closed by qqrz997** 2024-11-18 11:09 UTC
